name: "Analyze & Plan Terraform"

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  id-tf:
    name: Generate Plans
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/demo/terraform
    environment: "main"
    env:
      ARM_TENANT_ID: "${{ vars.ARM_TENANT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ vars.AZURE_STORAGE_SUBSCRIPTION_ID}}"
      ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
      ARM_USE_OIDC: "true"
      ARM_USE_AZUREAD: true
      STORAGE_ACCOUNT_NAME: "${{ vars.AZURE_TF_STATE_STORAGE_ACCOUNT_NAME }}"
      STORAGE_CONTAINER_NAME: "${{ vars.AZURE_STORAGE_CONTAINER_NAME }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: 1.15.8

      - name: Install Requirements
        id: install-requirements
        run: |
          sudo "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sudo brew install conftest

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: terraform-init
        run: |
          terraform init -backend-config="storage_account_name=${STORAGE_ACCOUNT_NAME}" \
                         -backend-config="container_name=${STORAGE_CONTAINER_NAME}" \
                         -backend-config="key=terraform.tfstate" \
                         -input=false \
                         -lock=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Generate Terraform Plans
        id: generate-tf-plans
        run: |
          terraform plan -refresh=false -out=plan.tfapply -input=false -detailed-exitcode -no-color
        continue-on-error: true

      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.generate-tf-plans.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
            })

            // 2. Prepare format of the comment
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.terraform-init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.generate-tf-plans.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }