name: "Analyze & Plan Terraform"

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  id-tf:
    name: Generate Plans
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/terraform
    env:
      ARM_TENANT_ID: "${{ vars.ARM_TENANT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ vars.AZURE_STORAGE_SUBSCRIPTION_ID}}"
      ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
      ARM_USE_OIDC: "true"
      ARM_USE_AZUREAD: true
      STORAGE_ACCOUNT_NAME: "${{ vars.AZURE_TF_STATE_STORAGE_ACCOUNT_NAME }}"
      STORAGE_CONTAINER_NAME: "${{ vars.AZURE_STORAGE_CONTAINER_NAME }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: 1.15.8


      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: terraform-init
        env:
          DEBUG: ${{ runner.debug }}
          TF_LOG_PROVIDER: "${{ runner.debug == '1' && 'DEBUG' || 'ERROR' }}"
        run: |
          terraform init -input=false -lock=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Generate Terraform Plans
        id: generate-tf-plans
        run: |
          terraform plan -refresh=false -out=plan.tfapply -input=false -detailed-exitcode

      - name: Upload Terraform plans
        uses: actions/upload-artifact@v7
        with:
          name: tfplan
          if-no-files-found: ignore
          path: |
            ./**/plan.tfapply
            